#%RAML 0.8
title: ANZ_user_info

protocols: [https]

/getProfiles:
  get:
    queryParameters:
      user_ref:
        displayName: user_ref
        type: string

      guid:
        displayName: guid
        type: string

      userId:
        displayName: user_ID
        type: string

      geoLocation:
        type: string


    responses:
      200:
        body:
          application/json:
            example: |
              {"header":{
                "user_ref":"",
                "guid":"",
                 "requestedOn":"",
                  "requestedFrom" :"",
                  "geoLocation":"",
                 "userid" :""
                 },


                         "body":{
                        "user_ref" : "123456",
                        "user_ID" : "123456",
                        "profile_for" : "123456",
                        "email_id" : "123456",
                        "first_name" : "123456",
                        "last_name" : "123456",
                        "gender" : "123456",
                        "dob" : "123456",
                        "height" : "123456",
                        "weight" : "123456",
                        "body_type" : "123456",
                        "diet" : "123456",
                        "drink" : "123456",
                       "smoke" : "123456",
                       "marital_status" : "123456",
                        "religion" : "123456",
                        "community" : "123456",
                        "sub_community" : "123456",
                        "fb_id" : "123456",
                        "twitter_id" : "123456",
                        "linkedin_id" : "123456",
                        "home_phone" : "123456",
                        "mobile_phone" : "123456",
                        "mother_tongue" : "123456",
                        "education_level" : "123456",
                        "working_organization" : "123456",
                        "designation" : "123456",
                        "income" : "123456",
                        "country" : "123456",
                        "state" : "123456",
                        "city" : "123456",
                        "express" : "123456",
                        "profile_type" : "123456"}

                        }
/updateProfile:
  put:
    responses:
      200:
        body:
          application/json:
            example: |
              {"header":{
                "user_ref":"",
                "guid":"",
                 "requestedOn":"",
                  "requestedFrom" :"",
                  "geoLocation":"",
                 "userid" :""
                 },


              "body":{
              "user_ref" : "123456",
              "user_ID" : "123456",
              "profile_for" : "123456",
              "email_id" : "123456",
              "first_name" : "123456",
              "last_name" : "123456",
              "gender" : "123456",
              "dob" : "123456",
              "height" : "123456",
              "weight" : "123456",
              "body_type" : "123456",
              "diet" : "123456",
              "drink" : "123456",
              "smoke" : "123456",
              "marital_status" : "123456",
              "religion" : "123456",
              "community" : "123456",
              "sub_community" : "123456",
              "fb_id" : "123456",
              "twitter_id" : "123456",
              "linkedin_id" : "123456",
              "home_phone" : "123456",
              "mobile_phone" : "123456",
              "mother_tongue" : "123456",
              "education_level" : "123456",
              "working_organization" : "123456",
              "designation" : "123456",
              "income" : "123456",
              "country" : "123456",
              "state" : "123456",
              "city" : "123456",
              "express" : "123456",
              "profile_type" : "123456"
              }

              }

              responses:
                200:
                  body:
                    application/json:
                      example: |
                        {"header":
                          {
                          "user_ref":"",
                          "guid":"",
                          "requestedOn":"",
                          "requestedFrom" :"",
                          "geoLocation":"",
                          "userid" :""
                           },
                      body:
                          {
                            "result":"successfully updated"
                          }
                        }

/createProfile:
  post:
    responses:
      200:

        body:
          application/json:
           example: |
             {"header":{
              "user_ref":"",
              "userid" :"",
              "guid":"",
              "requestedOn":"",
              "requestedFrom" :"",
               "geoLocation":""
              },

                  "body":{

                "user_ref" : "123456",
                "user_ID" : "123456",
                "first_name" : "123456",
                "last_name" : "123456",
                "gender" : "123456",
                "dob" : "123456",
                "height" : "123456",
                "weight" : "123456",
                "body_type" : "123456",
                "diet" : "123456",
                "drink" : "123456",
                "smoke" : "123456",
                "marital_status" : "123456",
                "religion" : "123456",
                "community" : "123456",
                "sub_community" : "123456",
                "fb_id" : "123456",
                "twitter_id" : "123456",
                "linkedin_id" : "123456",
                "home_phone" : "123456",
                "mobile_phone" : "123456",
                "mother_tongue" : "123456",
                "education_level" : "123456",
                "working_organization" : "123456",
                "designation" : "123456",
                "income" : "123456",
                "country" : "123456",
                "state" : "123456",
               "city" : "123456",
                "express" : "123456",
               "profile_type" : "123456"
              }

                }


                responses:
                  200:
                    body:
                      application/json:
                        example: |
                          {"header":{
                            "user_ref":"",
                            "guid":"",
                             "requestedOn":"",
                              "requestedFrom" :"",
                              "geoLocation":"",
                             "userid" :""
                             },
                    body:

                          {
                            "result":"successfully created"
                          }
                        }
